#!/bin/bash
set -e

function cdir() {
        if [ -d "$1" ]; then
                rm -rf "$1"
        fi
        mkdir "$1"
}

cdir "build"
cdir "install"

export VSXU_BUILD_BASE_PATH=$PWD
cd build
PKG_CONFIG_PATH= cmake ../../../vsxu/ -DVSXU_DEBUG=1 -DCMAKE_INSTALL_PREFIX=$VSXU_BUILD_BASE_PATH/install
VERBOSE=1 make -j8 install
