#!/bin/bash
if [ -d build ]; then
rm -rf build
mkdir build
else
mkdir build
fi
if [ -d install ]; then
rm -rf install
mkdir install
else
mkdir install
fi
export VSXU_BUILD_BASE_PATH=$PWD
cd build
cmake ../../../vsxu/ -DCMAKE_INSTALL_PREFIX=$VSXU_BUILD_BASE_PATH/install
make -j8 install
