#!/bin/bash
if [ -d build_static ]; then
rm -rf build_static
mkdir build_static
else
mkdir build_static
fi
if [ -d install_static ]; then
rm -rf install_static
mkdir install_static
else
mkdir install_static
fi
export VSXU_BUILD_BASE_PATH=$PWD
cd build_static
cmake ../../../vsxu/ -DCMAKE_INSTALL_PREFIX=$VSXU_BUILD_BASE_PATH/install_static -DVSXU_STATIC=1
cmake ../../../vsxu/ -DCMAKE_INSTALL_PREFIX=$VSXU_BUILD_BASE_PATH/install_static -DVSXU_STATIC=1
make -j8 install
