#!/bin/bash

set -e

function cdir() {
        if [ -d "$1" ]; then
                rm -rf "$1"
        fi
        mkdir "$1"
}

cdir "build_static"
cdir "install_static"

export VSXU_BUILD_BASE_PATH=$PWD
export VSXU_DEPINST=$PWD/dependencies-install
export CPATH=$VSXU_DEPINST/include
cd build_static
cmake -DCMAKE_TOOLCHAIN_FILE=$VSXU_BUILD_BASE_PATH/cmake/Toolchain-mingw64.cmake -DCMAKE_INSTALL_PREFIX=$VSXU_BUILD_BASE_PATH/install_static/ ../../../vsxu/ -DVSXU_STATIC=1
cmake -DCMAKE_TOOLCHAIN_FILE=$VSXU_BUILD_BASE_PATH/cmake/Toolchain-mingw64.cmake -DCMAKE_INSTALL_PREFIX=$VSXU_BUILD_BASE_PATH/install_static/ ../../../vsxu/ -DVSXU_STATIC=1
echo $CPATH
VERBOSE=1 make -j8 install
