#!/bin/bash

set -e

function cdir() {
        if [ -d "$1" ]; then
                rm -rf "$1"
        fi
        mkdir "$1"
}

cdir "build"

export VSXU_BUILD_BASE_PATH=$PWD
export LIB="C:\\Program Files \(x86\)\\Microsoft Visual Studio 14.0\\VC\\lib\\amd64"
#export VSXU_DEPINST=$PWD/dependencies-install
#export CPATH=$VSXU_DEPINST/include
##############################################
cd build
cmake -DCMAKE_GENERATOR="NMake Makefiles" \
 -DCMAKE_LIBRARY_PATH="/c/Program Files (x86)/Microsoft Visual Studio 14.0/VC/lib/amd64" \
 -DCMAKE_BUILD_TYPE=RelWithDebInfo \
 -DCMAKE_INSTALL_PREFIX=$VSXU_BUILD_BASE_PATH/install/ \
 -DCMAKE_EXE_LINKER_FLAGS="/machine:x64" \
 -DCMAKE_EXE_LINKER_FLAGS="/machine:x64" \
 ../../../vsxu/
echo $CPATH
jom && cpack -G NSIS
