#!/bin/bash
if [ -d build ]; then
echo build exists
rm -rf build
mkdir build
else
mkdir build
fi
export VSXU_BUILD_BASE_PATH=$PWD
export VSXU_DEPINST=$PWD/dependencies-install
export CPATH=$VSXU_DEPINST/include
export LIBRARY_PATH=$VSXU_DEPINST/lib
echo $VSXU_DEPINST
cd build
#cmake --debug-output --debug-trycompile -DCMAKE_TOOLCHAIN_FILE=$VSXU_BUILD_BASE_PATH/cmake/Toolchain-mingw64.cmake -DCMAKE_INSTALL_PREFIX=$VSXU_BUILD_BASE_PATH/install/ ../../../vsxu/
cmake -DCMAKE_TOOLCHAIN_FILE=$VSXU_BUILD_BASE_PATH/cmake/Toolchain-mingw64.cmake -DCMAKE_INSTALL_PREFIX=$VSXU_BUILD_BASE_PATH/install/ ../../../vsxu/
echo $CPATH
VERBOSE=1 LIBRARY_PATH=$VSXU_DEPINST/lib LINK_LIBRARIES=pthread make -j8
